/**
 * Identity helpers shared by the passkey + chat flows.
 *
 * A user who has just registered a passkey starts out with a synthetic email
 * of the form `passkey-<uuid>@local.invalid` (generated by
 * ensureSessionForPasskey() in `lib/passkey.ts`). The address is reserved
 * (RFC 6761 reserves `.invalid` TLD for tests), so it never routes mail
 * anywhere real. We treat it as "unassociated" — the user can sign in but
 * can't yet be addressed by another user, and shouldn't be allowed to start
 * chats until they've supplied a real email through the associate-email
 * flow.
 */
const BOOTSTRAP_EMAIL_RE = /^passkey-[0-9a-f-]+@local\.invalid$/i;

export function isBootstrapEmail(email: string | null | undefined): boolean {
  if (!email) {
    return false;
  }
  return BOOTSTRAP_EMAIL_RE.test(email.trim().toLowerCase());
}
